---  # yml 파일이라는 의미

name: Checks

on: [push]  # 트리거. Github에 push하면 jobs가 실행됨

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.8"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        touch .env
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
      working-directory: ./src

    - name: Run tests
      run: |
        python manage.py migrate
        pytest
      working-directory: ./src
