---  # yml 파일이라는 의미

name: Checks

on: [push]  # 트리거. Github에 push하면 jobs가 실행됨

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.8"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        pytest
      working-directory: ./src
